### ISSUE TITLE
ACT client does not handle expired proxies properly

### ISSUE THREAD

**Issue by ntadej** [ARCControlTower/aCT#79] opened 2020-05-11 08:25 UTC
ACT client does not handle expired proxies properly. I has to restart server for jobs to continue submitting.

To reproduce:
 - setup arc proxy and run `actproxy`
 - submit some jobs
 - wait for the proxy to expire
 - make a new proxy and run `actproxy`
 - server will still report proxy as expired

/cc @jakobmerljak

**Comment by jakobmerljak** [comment] 2020-05-13 17:33
I could not reproduce your issue. I did, however, fix proxy handling as client commands could work with updated proxy file and outdated database entry of the proxy. The fix is in #82.

Which part of aCT reports that the proxy is expired? Was that a client command (output) or process (log file)?

**Comment by ntadej** [comment] 2020-05-13 17:35
It was aCTSubmitter. I saw it in the log when no jobs were submitting. Once I restarted the server, things moved as expected.

**Comment by jakobmerljak** [comment] 2020-05-13 17:50
I tried to reproduce this by using very short-lived certificates (30 seconds). aCTSubmitter reports that proxy is expired. After the proxy is updated, it resumes submission normally.

Do you have a specific log message or log file that aCTSubmitter emitted?

**Closed** 2020-12-04 21:06 UTC
